# Generated by Django 4.1.4 on 2022-12-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='upload',
            field=models.FileField(blank=True, upload_to='personal_portfolio/uploads/'),
        ),
    ]
